import { bitable, type IAttachmentField, type IGridView, type IOpenAttachment } from "@lark-base-open/js-sdk";
import * as pdfjs from "pdfjs-dist";
import pdfWorker from "pdfjs-dist/build/pdf.worker.min.mjs?url";
import { createWorker, type Worker } from "tesseract.js";
import * as XLSX from "xlsx";
import "./style.css";

pdfjs.GlobalWorkerOptions.workerSrc=pdfWorker;
const FIELD={treasury:"小金库",header:"发票抬头",category:"报销类目",source:"发票+订单截图+支付截图",reason:"报销事由"} as const;
const TAX={university:{name:"浙江大学",code:"12100000470095016Q"},foundation:{name:"浙江大学教育基金会",code:"53100000500020171G"}} as const;
const FORBIDDEN=["文创","会员费","软件会员","食品","餐饮","零食","饮料","耳机","鼠标","纸巾","日用品","家居","椅子","置物架","家具"];
const ENTERTAINMENT=["轰趴","商场","ktv","酒吧","景区","影院","电影院","烧烤","餐厅","饭店","火锅","娱乐"];
const CAMPUS=["浙江大学","紫金港","玉泉","华家池","之江校区","西溪校区","海宁国际校区","舟山校区"];
const CURRENT_YEAR=new Date().getFullYear();
const app=document.querySelector<HTMLElement>("#app")!;
app.innerHTML=`<main class="shell"><header><span class="eyebrow">X-LAB 财务工具</span><h1>报销材料审核</h1><p>勾选一条记录，插件将按照发票抬头、报销类目和附件内容逐项核对。</p></header><section class="card selection"><div><strong id="selection">正在读取所选记录……</strong><small>一次审核一条记录，结果仅展示在插件页面</small></div><button id="refresh" class="secondary">重新读取</button></section><button id="review" class="primary" disabled>开始审核所选记录</button><div class="progress"><span id="bar"></span></div><div id="status" class="status" aria-live="polite"></div><section id="result"></section><p class="footnote">自动识别无法替代最终人工审批；无法可靠读取的项目会明确显示为未勾选并提示人工确认。</p></main>`;

const el=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
const selectionEl=el<HTMLElement>("#selection"),reviewBtn=el<HTMLButtonElement>("#review"),refreshBtn=el<HTMLButtonElement>("#refresh"),statusEl=el<HTMLElement>("#status"),bar=el<HTMLElement>("#bar"),resultEl=el<HTMLElement>("#result");
type Page={file:string,page:number,text:string,ocr:boolean};
type Workbook={file:string,text:string};
type Check={title:string;pass:boolean;detail:string;evidence?:string};
type ReviewInput={recordId:string;reason:string;treasury:string;header:string;category:string;files:IOpenAttachment[];urls:string[]};
let input:ReviewInput|null=null;let workerPromise:Promise<Worker>|null=null;
function setStatus(message:string,kind:"info"|"success"|"error"="info"){statusEl.textContent=message;statusEl.className=`status ${kind}`;}
function progress(done:number,total:number){bar.style.width=total?`${Math.min(100,done/total*100)}%`:"0%";}
function safe(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));}
function norm(v:string){return v.toLowerCase().replace(/[\s，,。；;：:（）()【】\[\]_-]/g,"");}
function has(text:string,words:string[]){const n=norm(text);return words.some(w=>n.includes(norm(w)));}
function clip(text:string,words:string[]){const plain=text.replace(/\s+/g," ").trim();const lower=plain.toLowerCase();const found=words.map(w=>lower.indexOf(w.toLowerCase())).find(i=>i>=0)??-1;return (found<0?plain.slice(0,130):plain.slice(Math.max(0,found-35),found+100));}
async function ocrWorker(){if(!workerPromise)workerPromise=createWorker("chi_sim+eng",1,{logger:m=>{if(m.status==="recognizing text")setStatus(`正在 OCR：${Math.round((m.progress||0)*100)}%`);}});return workerPromise;}
async function ocrCanvas(canvas:HTMLCanvasElement){const worker=await ocrWorker();return (await worker.recognize(canvas)).data.text.trim();}
async function parsePdf(file:string,buffer:ArrayBuffer){const doc=await pdfjs.getDocument({data:buffer}).promise;const pages:Page[]=[];for(let i=1;i<=doc.numPages;i++){setStatus(`正在识别 ${file}：第 ${i}/${doc.numPages} 页`);const page=await doc.getPage(i);const content=await page.getTextContent();let text=content.items.map(item=>("str" in item?item.str:"")).join(" ").trim();let ocr=false;if(text.replace(/\s/g,"").length<25){const viewport=page.getViewport({scale:1.55});const canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext("2d");if(ctx){await page.render({canvasContext:ctx,viewport}).promise;text=`${text} ${await ocrCanvas(canvas)}`.trim();ocr=true;}}pages.push({file,page:i,text,ocr});}return pages;}
async function parseImage(file:string,blob:Blob){const url=URL.createObjectURL(blob);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url;});const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext("2d")?.drawImage(image,0,0);return {file,page:1,text:await ocrCanvas(canvas),ocr:true} as Page;}finally{URL.revokeObjectURL(url);}}
function parseWorkbook(file:string,buffer:ArrayBuffer){const book=XLSX.read(buffer,{type:"array",cellDates:true});const text=book.SheetNames.map(name=>XLSX.utils.sheet_to_csv(book.Sheets[name],{FS:" | "})).join("\n");return {file,text} as Workbook;}
function isPdf(f:IOpenAttachment){return f.name.toLowerCase().endsWith(".pdf")||/pdf/i.test(f.type)}
function isImage(f:IOpenAttachment){return /image/i.test(f.type)||/\.(png|jpe?g|webp)$/i.test(f.name)}
function isExcel(f:IOpenAttachment){return /\.(xlsx?|csv)$/i.test(f.name)}
function kind(category:string){if(/打车|市内交通/.test(category))return"local";if(/高铁|火车/.test(category))return"rail";if(/飞机|机票|航空/.test(category))return"flight";if(/耗材|设备|配件|文印|办公用品/.test(category))return"goods";return"other";}
function pageHas(page:Page,type:"invoice"|"order"|"payment"|"itinerary"){const words={invoice:["发票号码","电子发票","增值税","价税合计","购买方信息"],order:["订单编号","订单详情","商品名称","下单时间","实付款"],payment:["支付成功","交易成功","付款成功","支付时间","微信支付","支付宝"],itinerary:["行程单","行程信息","上车时间","起点","终点","出发地","目的地"]}[type];return has(page.text,words);}
function invoiceAmounts(pages:Page[]){const values:number[]=[];for(const p of pages.filter(p=>pageHas(p,"invoice"))){const text=p.text.replace(/,/g,"");for(const re of [/价税合计[^\d]{0,18}(\d+(?:\.\d{1,2})?)/g,/小写[^\d]{0,12}(\d+(?:\.\d{1,2})?)/g,/含税金额[^\d]{0,12}(\d+(?:\.\d{1,2})?)/g]){for(const match of text.matchAll(re)){const n=Number(match[1]);if(Number.isFinite(n))values.push(n);}}}return values;}
function excelChecks(books:Workbook[]){const text=books.map(b=>b.text).join("\n");const required=["时间","往返地点","往返总金额","差旅人员","差旅原因"];const missing=required.filter(x=>!text.includes(x));const hasStudent=/\d{8,}/.test(text);const closed=/杭州.{0,12}[-至到].{1,12}/.test(text)&&has(text,["往返","返程","时间"]);return {present:books.length>0,complete:books.length>0&&!missing.length&&hasStudent,closed,missing,text};}
function baseChecks(data:ReviewInput,pages:Page[],pageCount:number){const checks:Check[]=[];const all=pages.map(p=>p.text).join("\n");const expected=data.header.includes("基金会")?TAX.foundation:TAX.university;checks.push({title:"发票抬头与表格字段一致",pass:norm(all).includes(norm(expected.name)),detail:`表格选择“${data.header}”，附件中应出现“${expected.name}”。`,evidence:clip(all,[expected.name])});checks.push({title:"纳税人识别号正确",pass:norm(all).includes(norm(expected.code)),detail:`${expected.name}税号应为 ${expected.code}。`,evidence:clip(all,[expected.code])});checks.push({title:"单个材料文件少于30页",pass:pageCount<30,detail:`当前PDF材料共 ${pageCount} 页；规则要求单文件少于30页。`});return checks;}
function goodsChecks(pages:Page[]){const checks:Check[]=[];const invoices=pages.filter(p=>pageHas(p,"invoice"));const paired=invoices.length>0&&invoices.every(invoice=>{const next=pages.find(p=>p.file===invoice.file&&p.page===invoice.page+1);return !!next&&pageHas(next,"order")&&pageHas(next,"payment");});const mixed=invoices.some(p=>pageHas(p,"order")||pageHas(p,"payment"));const all=pages.map(p=>p.text).join("\n");const forbidden=FORBIDDEN.filter(x=>has(all,[x]));checks.push({title:"发票与订单/支付截图按页配对",pass:paired&&!mixed,detail:"每张发票单独一页，下一页同时放订单截图和支付截图。",evidence:`识别到 ${invoices.length} 个发票页；${paired?"相邻材料页结构完整":"存在未识别到订单+支付截图的发票"}${mixed?"；发现发票与截图疑似混在同页":""}`});checks.push({title:"不含个人性质或禁止报销物品",pass:forbidden.length===0,detail:"文创、会员费、食品、耳机、鼠标、纸巾、日用品、家居和家具类不能按材料费报销。",evidence:forbidden.length?`识别到：${forbidden.join("、")}`:"未识别到禁止关键词"});return checks;}
function localChecks(pages:Page[]){const checks:Check[]=[];const invoices=pages.filter(p=>pageHas(p,"invoice")),trips=pages.filter(p=>pageHas(p,"itinerary"));const all=pages.map(p=>p.text).join("\n");const separated=invoices.length>0&&trips.length>0&&!invoices.some(p=>pageHas(p,"itinerary"));checks.push({title:"发票与行程单齐全且分开放置",pass:separated,detail:"需同时提供发票和行程单，并分开页面放置。",evidence:`识别到发票页 ${invoices.length} 个、行程页 ${trips.length} 个`});const campus=CAMPUS.filter(x=>has(all,[x]));checks.push({title:"每段行程至少一端为浙江大学校区",pass:campus.length>0,detail:"起点或终点必须至少有一个在浙江大学校区内。",evidence:campus.length?`识别到：${campus.join("、")}`:"未识别到浙江大学校区名称，请人工核对行程单"});const invoiceText=invoices.map(p=>p.text).join("\n");checks.push({title:`发票开票时间在${CURRENT_YEAR}年内`,pass:invoiceText.includes(String(CURRENT_YEAR)),detail:`发票页应能识别到 ${CURRENT_YEAR} 年的开票日期。`,evidence:clip(invoiceText,[String(CURRENT_YEAR)])});const amounts=invoiceAmounts(pages);checks.push({title:"单张发票含税金额不超过200元",pass:amounts.length>0&&amounts.every(n=>n<=200),detail:"任一张发票含税金额大于200元均不能报销。",evidence:amounts.length?`识别金额：${amounts.map(n=>`¥${n.toFixed(2)}`).join("、")}`:"未能可靠识别价税合计，请人工确认"});const bad=ENTERTAINMENT.filter(x=>has(all,[x]));checks.push({title:"目的地不属于餐饮、娱乐或景区",pass:bad.length===0,detail:"轰趴、商场、KTV、酒吧、景区等目的地不能报销。",evidence:bad.length?`识别到：${bad.join("、")}`:"未识别到禁止目的地关键词"});const station=has(all,["机场","火车站","高铁站","铁路杭州站","杭州东站","杭州西站"]);const travel=has(all,["火车票","铁路电子客票","航班","机票","航空运输"]);checks.push({title:"车站/机场行程与对应差旅材料一起提交",pass:!station||travel,detail:"前往车站或机场的行程不能单独报销，必须与高铁或飞机差旅一起提交。",evidence:station?(travel?"识别到车站/机场及对应差旅材料":"识别到车站/机场，但未识别到高铁或飞机材料"):"未识别到车站或机场行程"});return checks;}
function railChecks(pages:Page[],books:Workbook[]){const checks:Check[]=[];const all=pages.map(p=>p.text).join("\n");const excel=excelChecks(books);const second=has(all,["二等座","二等" ]),first=has(all,["一等座","一等"]),exception=has(all,["情况说明"])&&has(all,["二等票价","二等座票价"]);checks.push({title:"乘坐席别符合二等座要求",pass:second||(!second&&first&&exception),detail:"应乘坐二等座；一等座需附情况说明和二等座票价截图。",evidence:second?"识别到二等座":first?(exception?"识别到一等座及例外材料":"识别到一等座，但缺少情况说明或二等座票价截图"):"未识别到席别"});checks.push({title:"电子发票PDF已提交",pass:pages.some(p=>pageHas(p,"invoice")),detail:"高铁报销需提供电子发票PDF。",evidence:`识别到 ${pages.filter(p=>pageHas(p,"invoice")).length} 个发票页`});checks.push({title:"差旅Excel字段完整",pass:excel.complete,detail:"Excel需含时间、往返地点、往返总金额、差旅人员（姓名、学号）和差旅原因。",evidence:excel.present?(excel.missing.length?`缺少：${excel.missing.join("、")}；并检查姓名/学号` : "已识别要求字段和学号"):"未发现Excel附件"});checks.push({title:"往返行程形成闭环",pass:excel.closed,detail:"应从杭州出发并返回杭州。",evidence:excel.present?clip(excel.text,["往返地点","杭州"]):"未发现Excel附件"});return checks;}
function flightChecks(pages:Page[],books:Workbook[]){const checks:Check[]=[];const all=pages.map(p=>p.text).join("\n");const excel=excelChecks(books);checks.push({title:"发票或纸质行程单已提交",pass:pages.some(p=>pageHas(p,"invoice")||pageHas(p,"itinerary")),detail:"可提交电子/纸质发票原件；无发票时可用纸质行程单。"});const order=has(all,["订单","航班号","航班"]),identity=has(all,["姓名","乘机人","旅客"]),route=has(all,["出发地","目的地","起飞","到达"]),economy=has(all,["经济舱","经济舱位"]);checks.push({title:"订单截图信息完整且为经济舱",pass:order&&identity&&route&&economy,detail:"订单截图需体现姓名、起终点、航班号和经济舱舱位，并证明由填报学号人员乘坐。",evidence:`订单/航班 ${order?"✓":"×"}；姓名 ${identity?"✓":"×"}；起终点 ${route?"✓":"×"}；经济舱 ${economy?"✓":"×"}`});checks.push({title:"支付截图已提交",pass:pages.some(p=>pageHas(p,"payment")),detail:"飞机票材料需包含支付截图。",evidence:`识别到 ${pages.filter(p=>pageHas(p,"payment")).length} 个支付页`});checks.push({title:"差旅Excel字段完整",pass:excel.complete,detail:"Excel需含时间、往返地点、往返总金额、差旅人员（姓名、学号）和差旅原因。",evidence:excel.present?(excel.missing.length?`缺少：${excel.missing.join("、")}`:"已识别要求字段和学号"):"未发现Excel附件"});checks.push({title:"往返行程形成闭环",pass:excel.closed,detail:"应从杭州出发并返回杭州。",evidence:excel.present?clip(excel.text,["往返地点","杭州"]):"未发现Excel附件"});return checks;}
async function readSelection(){const table=await bitable.base.getActiveTable();const view=await table.getActiveView() as IGridView;const ids=await view.getSelectedRecordIdList();if(ids.length!==1)throw new Error(ids.length?"请只勾选一条记录进行审核":"请先在表格左侧勾选一条记录");const [treasury,header,category,source,reason]=await Promise.all([table.getFieldByName(FIELD.treasury),table.getFieldByName(FIELD.header),table.getFieldByName(FIELD.category),table.getFieldByName<IAttachmentField>(FIELD.source),table.getFieldByName(FIELD.reason)]);const recordId=ids[0];const [treasuryText,headerText,categoryText,reasonText,files,urls]=await Promise.all([treasury.getCellString(recordId),header.getCellString(recordId),category.getCellString(recordId),reason.getCellString(recordId),source.getValue(recordId),source.getAttachmentUrls(recordId)]);return {recordId,reason:reasonText.trim(),treasury:treasuryText.trim(),header:headerText.trim(),category:categoryText.trim(),files,urls} as ReviewInput;}
async function refresh(){try{input=await readSelection();selectionEl.textContent=`${input.reason||"未填写报销事由"}｜${input.category||"未选择类目"}`;reviewBtn.disabled=false;setStatus("");resultEl.innerHTML="";}catch(error){input=null;selectionEl.textContent=error instanceof Error?error.message:String(error);reviewBtn.disabled=true;}}
function render(data:ReviewInput,checks:Check[],skipped=false){const passed=checks.filter(c=>c.pass).length,allPass=checks.length>0&&passed===checks.length;const cls=skipped?"skip":allPass?"pass":"fail";resultEl.innerHTML=`<section class="card summary ${cls}"><h2>${skipped?"无需预审":allPass?"预审通过":"预审未通过 / 需人工确认"}</h2><p>${skipped?"该记录标记为小金库，不分析报销材料。":`通过 ${passed}/${checks.length} 项；未勾选项目请查看原因。`}</p><div class="meta"><span>报销事由</span><b>${safe(data.reason||"未填写")}</b><span>发票抬头</span><b>${safe(data.header||"未填写")}</b><span>报销类目</span><b>${safe(data.category||"未填写")}</b><span>材料附件</span><b>${data.files.length} 个</b></div></section>${skipped?"":`<section class="checks">${checks.map(c=>`<article class="check ${c.pass?"pass":"fail"}"><span class="icon">${c.pass?"✓":"×"}</span><div><h3>${safe(c.title)}</h3><p>${safe(c.detail)}</p>${c.evidence?`<p class="evidence">识别依据：${safe(c.evidence)}</p>`:""}</div></article>`).join("")}</section>`}`;}
async function review(){if(!input)return;reviewBtn.disabled=true;refreshBtn.disabled=true;resultEl.innerHTML="";try{if(input.treasury.includes("是")){render(input,[],true);setStatus("该记录属于小金库，已按规则跳过材料分析。","success");return;}if(!input.header||!input.category)throw new Error("请先填写发票抬头和报销类目");if(!input.files.length)throw new Error("未找到报销材料附件");const pages:Page[]=[],books:Workbook[]=[];let pdfPages=0;for(let i=0;i<input.files.length;i++){const file=input.files[i],url=input.urls[i];setStatus(`正在读取 ${i+1}/${input.files.length}：${file.name}`);const response=await fetch(url);if(!response.ok)throw new Error(`附件下载失败：${file.name}`);const buffer=await response.arrayBuffer();if(isPdf(file)){const parsed=await parsePdf(file.name,buffer);pages.push(...parsed);pdfPages+=parsed.length;}else if(isImage(file)){pages.push(await parseImage(file.name,new Blob([buffer],{type:file.type})));}else if(isExcel(file)){books.push(parseWorkbook(file.name,buffer));}progress(i+1,input.files.length);}let checks=baseChecks(input,pages,pdfPages);const type=kind(input.category);if(type==="goods")checks.push(...goodsChecks(pages));else if(type==="local")checks.push(...localChecks(pages));else if(type==="rail")checks.push(...railChecks(pages,books));else if(type==="flight")checks.push(...flightChecks(pages,books));else checks.push({title:"报销类目已配置专项规则",pass:false,detail:`当前版本尚未配置“${input.category}”的专项规则，请人工审核。`});render(input,checks);setStatus(checks.every(c=>c.pass)?"所有规则均已通过。":"审核完成，请处理未勾选项目。",checks.every(c=>c.pass)?"success":"error");}catch(error){setStatus(error instanceof Error?error.message:String(error),"error");}finally{reviewBtn.disabled=!input;refreshBtn.disabled=false;}}
refreshBtn.onclick=refresh;reviewBtn.onclick=review;void refresh();
