import { bitable, type IAttachmentField, type IGridView, type IOpenAttachment } from "@lark-base-open/js-sdk";
import * as pdfjs from "pdfjs-dist";
import pdfWorker from "pdfjs-dist/build/pdf.worker.min.mjs?url";
import { createWorker, type Worker } from "tesseract.js";
import * as XLSX from "xlsx";
import "./style.css";

pdfjs.GlobalWorkerOptions.workerSrc=pdfWorker;
const FIELD={treasury:"小金库",header:"发票抬头",category:"报销类目",source:"发票+订单截图+支付截图",reason:"报销事由"} as const;
const TAX={university:{name:"浙江大学",code:"12100000470095016Q"},foundation:{name:"浙江大学教育基金会",code:"53100000500020171G"}} as const;
const FORBIDDEN=["文创","会员费","软件会员","食品","餐饮","零食","饮料","耳机","鼠标","纸巾","日用品","家居","椅子","置物架","家具"];
const RISKY_POI=["轰趴","商场","ktv","酒吧","景区","影院","电影院","烧烤","餐厅","饭店","火锅","娱乐","天街","银泰","万象城","印象城","大悦城","来福士","宝龙","吾悦","奥特莱斯","in77","商业中心","购物中心"];
const CAMPUS=["浙江大学","紫金港","玉泉","华家池","之江校区","西溪校区","海宁国际校区","舟山校区"];
const CURRENT_YEAR=new Date().getFullYear();
const app=document.querySelector<HTMLElement>("#app")!;
app.innerHTML=`<main class="shell"><header><span class="eyebrow">X-LAB 财务工具 · 分区金额审核 v1.5</span><h1>报销材料审核</h1><p>先勾选一条记录，再打开或刷新插件；系统会自动读取并开始审核。</p></header><section class="card selection"><div><strong id="selection">正在读取所选记录……</strong><small>一次审核一条记录，结果仅展示在插件页面</small></div><button id="refresh" class="secondary">读取并审核</button></section><button id="review" class="primary" disabled>重新审核当前记录</button><div class="progress"><span id="bar"></span></div><div id="status" class="status" aria-live="polite"></div><section id="result"></section><p class="footnote">自动识别无法替代最终人工审批；无法可靠读取的项目会明确显示为未勾选并提示人工确认。</p></main>`;

const el=<T extends HTMLElement>(q:string)=>document.querySelector<T>(q)!;
const selectionEl=el<HTMLElement>("#selection"),reviewBtn=el<HTMLButtonElement>("#review"),refreshBtn=el<HTMLButtonElement>("#refresh"),statusEl=el<HTMLElement>("#status"),bar=el<HTMLElement>("#bar"),resultEl=el<HTMLElement>("#result");
type Page={file:string,page:number,text:string,ocr:boolean,total?:number;regions?:string[]};
type Workbook={file:string,text:string};
type Check={title:string;pass:boolean;detail:string;evidence?:string};
type ReviewInput={recordId:string;reason:string;treasury:string;header:string;category:string;files:IOpenAttachment[];urls:string[]};
let input:ReviewInput|null=null;let workerPromise:Promise<Worker>|null=null;
function setStatus(message:string,kind:"info"|"success"|"error"="info"){statusEl.textContent=message;statusEl.className=`status ${kind}`;}
function progress(done:number,total:number){bar.style.width=total?`${Math.min(100,done/total*100)}%`:"0%";}
function safe(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]!));}
function norm(v:string){return v.toLowerCase().replace(/[\s，,。；;：:（）()【】\[\]_-]/g,"");}
function has(text:string,words:string[]){const n=norm(text);return words.some(w=>n.includes(norm(w)));}
function clip(text:string,words:string[]){const plain=text.replace(/\s+/g," ").trim();const lower=plain.toLowerCase();const found=words.map(w=>lower.indexOf(w.toLowerCase())).find(i=>i>=0)??-1;return (found<0?plain.slice(0,130):plain.slice(Math.max(0,found-35),found+100));}
async function ocrWorker(){if(!workerPromise)workerPromise=createWorker("chi_sim+eng",1,{logger:m=>{if(m.status==="recognizing text")setStatus(`正在 OCR：${Math.round((m.progress||0)*100)}%`);}});return workerPromise;}
async function ocrCanvas(canvas:HTMLCanvasElement){const worker=await ocrWorker();return (await worker.recognize(canvas)).data.text.trim();}
async function ocrCrop(source:HTMLCanvasElement,x:number,y:number,width:number,height:number){const crop=document.createElement("canvas");crop.width=Math.max(1,Math.round(width));crop.height=Math.max(1,Math.round(height));crop.getContext("2d")?.drawImage(source,x,y,width,height,0,0,crop.width,crop.height);return ocrCanvas(crop);}
async function ocrSupportRegions(canvas:HTMLCanvasElement){const w=canvas.width,h=canvas.height;const specs=[[0,0,w,h*.6],[0,h*.4,w,h*.6],[0,0,w*.6,h],[w*.4,0,w*.6,h]];const regions:string[]=[];for(let i=0;i<specs.length;i++){setStatus(`正在分区识别订单/支付截图 ${i+1}/${specs.length}`);regions.push(await ocrCrop(canvas,...specs[i] as [number,number,number,number]));}return regions.filter(Boolean);}
function numberFromText(text:string){const values=[...text.replace(/,/g,"").matchAll(/(?:[¥￥]\s*)?(\d{1,7}(?:\.\d{1,2})?)/g)].map(match=>Number(match[1])).filter(n=>Number.isFinite(n)&&n>0&&n<10000000);return values.length?Math.max(...values):null;}
function positionedInvoiceTotal(items:unknown[]){const parts=items.filter((item):item is {str:string;transform:number[]}=>typeof item==="object"&&item!==null&&"str" in item&&"transform" in item&&typeof (item as {str?:unknown}).str==="string"&&Array.isArray((item as {transform?:unknown}).transform)).map(item=>({text:item.str,x:item.transform[4]||0,y:item.transform[5]||0}));const lines:{y:number;parts:typeof parts}[]=[];for(const part of parts){let line=lines.find(row=>Math.abs(row.y-part.y)<=5);if(!line){line={y:part.y,parts:[]};lines.push(line);}line.parts.push(part);}for(const line of lines){line.parts.sort((a,b)=>a.x-b.x);const text=line.parts.map(part=>part.text).join("");if(!/小\s*写|价\s*税\s*合\s*计/.test(text))continue;const afterSmall=text.match(/小\s*写[）)]?\s*([\s\S]*)/)?.[1];const direct=afterSmall?numberFromText(afterSmall):null;if(direct!==null)return direct;const candidates=line.parts.map(part=>({x:part.x,value:numberFromText(part.text)})).filter((item):item is {x:number;value:number}=>item.value!==null).sort((a,b)=>b.x-a.x);if(candidates.length)return candidates[0].value;}return null;}
async function parsePdf(file:string,buffer:ArrayBuffer,categoryKind="other"){const doc=await pdfjs.getDocument({data:buffer}).promise;const pages:Page[]=[];for(let i=1;i<=doc.numPages;i++){setStatus(`正在识别 ${file}：第 ${i}/${doc.numPages} 页`);const page=await doc.getPage(i);const content=await page.getTextContent();let text=content.items.map(item=>("str" in item?item.str:"")).join(" ").trim();const positionedTotal=positionedInvoiceTotal(content.items);let ocr=false,regions:string[]|undefined;const looksLikeInvoice=has(text,["发票号码","电子发票","增值税","价税合计"]);const needsGoodsOcr=categoryKind==="goods"&&!looksLikeInvoice;if(text.replace(/\s/g,"").length<25||needsGoodsOcr||(looksLikeInvoice&&positionedTotal===null&&moneyValues(text).length===0)){const viewport=page.getViewport({scale:needsGoodsOcr?3:1.8});const canvas=document.createElement("canvas");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext("2d");if(ctx){await page.render({canvasContext:ctx,viewport}).promise;if(needsGoodsOcr){regions=await ocrSupportRegions(canvas);text=`${text} ${regions.join(" ")}`.trim();}else{text=`${text} ${await ocrCanvas(canvas)}`.trim();}ocr=true;}}pages.push({file,page:i,text,ocr,...(positionedTotal===null?{}:{total:positionedTotal}),...(regions?{regions}:{})});}return pages;}
async function parseImage(file:string,blob:Blob){const url=URL.createObjectURL(blob);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url;});const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext("2d")?.drawImage(image,0,0);return {file,page:1,text:await ocrCanvas(canvas),ocr:true} as Page;}finally{URL.revokeObjectURL(url);}}
function parseWorkbook(file:string,buffer:ArrayBuffer){const book=XLSX.read(buffer,{type:"array",cellDates:true});const text=book.SheetNames.map(name=>XLSX.utils.sheet_to_csv(book.Sheets[name],{FS:" | "})).join("\n");return {file,text} as Workbook;}
function isPdf(f:IOpenAttachment){return f.name.toLowerCase().endsWith(".pdf")||/pdf/i.test(f.type)}
function isImage(f:IOpenAttachment){return /image/i.test(f.type)||/\.(png|jpe?g|webp)$/i.test(f.name)}
function isExcel(f:IOpenAttachment){return /\.(xlsx?|csv)$/i.test(f.name)}
function kind(category:string){if(/打车|市内交通/.test(category))return"local";if(/高铁|火车/.test(category))return"rail";if(/飞机|机票|航空/.test(category))return"flight";if(/耗材|设备|配件|文印|办公用品/.test(category))return"goods";return"other";}
function pageScore(page:Page,type:"invoice"|"order"|"payment"|"itinerary"){const words={invoice:["发票号码","电子发票","增值税","价税合计","购买方信息","销售方信息"],order:["订单编号","订单号","订单详情","商品名称","商品信息","下单时间","购买时间","实付款","订单金额"],payment:["支付成功","交易成功","付款成功","支付时间","微信支付","支付宝","付款方式","支付凭证","交易单号","支付金额","付款金额"],itinerary:["行程单","行程信息","上车时间","下车时间","起点","终点","出发地","目的地","上车地点","下车地点"]}[type];return words.filter(word=>has(page.text,[word])).length;}
function pageHas(page:Page,type:"invoice"|"order"|"payment"|"itinerary"){const score=pageScore(page,type);if(type==="invoice")return score>=2||has(page.text,["发票号码"])&&has(page.text,["价税合计"]);if(type==="itinerary")return score>=2&&(score>=3||has(page.text,["行程单","行程信息"]))&&pageScore(page,"invoice")<3;return score>=2;}
function moneyValues(text:string){const clean=text.replace(/,/g,"");const labelled:number[]=[];const patterns=[/(?:价税合计|小写|含税金额|实付金额|实付款|实际支付|支付金额|付款金额|订单金额|费用合计|总金额)[\s\S]{0,70}?(?:[¥￥]\s*)?(\d{1,7}(?:\.\d{1,2})?)/gi,/[¥￥]\s*(\d{1,7}(?:\.\d{1,2})?)/g];for(const re of patterns){for(const match of clean.matchAll(re)){const n=Number(match[1]);if(Number.isFinite(n)&&n>0&&n<10000000)labelled.push(n);}}if(labelled.length)return [...new Set(labelled.map(n=>Number(n.toFixed(2))))];const decimals=[...clean.matchAll(/(?<!\d)(\d{1,6}\.\d{2})(?!\d)/g)].map(m=>Number(m[1])).filter(n=>n>0&&n<100000);return [...new Set(decimals.map(n=>Number(n.toFixed(2))))];}
function invoiceTotal(text:string){const clean=text.replace(/,/g,"");const patterns=[/[（(]?\s*小\s*写\s*[）)]?\s*(?:[¥￥]\s*)?(\d{1,7}(?:\.\d{1,2})?)/gi,/价\s*税\s*合\s*计[\s\S]{0,220}?[¥￥]\s*(\d{1,7}(?:\.\d{1,2})?)/gi];for(const re of patterns){const values=[...clean.matchAll(re)].map(match=>Number(match[1])).filter(n=>Number.isFinite(n)&&n>0&&n<10000000);if(values.length)return values.at(-1)!;}return null;}
function pageAmount(page:Page){if(pageHas(page,"invoice")){if(page.total!==undefined)return page.total;const total=invoiceTotal(page.text);if(total!==null)return total;}const values=moneyValues(page.text);return values.length?Math.max(...values):null;}
function invoiceAmounts(pages:Page[]){return pages.filter(p=>pageHas(p,"invoice")).map(pageAmount).filter((n):n is number=>n!==null);}
function amountsNear(text:string,labels:string[]){const compact=text.replace(/[\s,，]/g,"");const values:number[]=[];for(const label of labels){let start=0;while((start=compact.indexOf(label,start))>=0){const segment=compact.slice(start+label.length,start+label.length+100);const matches=[...segment.matchAll(/[¥￥]\s*(\d{1,7}(?:\.\d{1,2})?)|(?<!\d)(\d{1,6}\.\d{2})(?!\d)/g)];for(const match of matches.slice(0,2)){const value=Number(match[1]||match[2]);if(Number.isFinite(value)&&value>0&&value<10000000)values.push(Number(value.toFixed(2)));}start+=label.length;}}return [...new Set(values)];}
function supportAmounts(page:Page){const orderLabels=["实付款","订单金额","订单总额","合计"],paymentLabels=["支付金额","付款金额","交易金额","已支付","支付成功","付款成功","交易成功","微信支付","支付宝"];const regions=page.regions?.length?page.regions:[page.text];const ranked=regions.map((text,index)=>({text,index,order:pageScore({file:page.file,page:page.page,text,ocr:true},"order"),payment:pageScore({file:page.file,page:page.page,text,ocr:true},"payment")}));const orderRegion=[...ranked].sort((a,b)=>(b.order-b.payment)-(a.order-a.payment)||b.order-a.order)[0];const paymentRegion=[...ranked].filter(region=>region.index!==orderRegion?.index).sort((a,b)=>(b.payment-b.order)-(a.payment-a.order)||b.payment-a.payment)[0]||orderRegion;let order=orderRegion?amountsNear(orderRegion.text,orderLabels):[],payment=paymentRegion?amountsNear(paymentRegion.text,paymentLabels):[];if(!order.length&&orderRegion)order=moneyValues(orderRegion.text);if(!payment.length&&paymentRegion)payment=moneyValues(paymentRegion.text);return {order,payment,orderRegion:(orderRegion?.index??-1)+1,paymentRegion:(paymentRegion?.index??-1)+1};}
function amountConsistencyCheck(pages:Page[],types:("invoice"|"order"|"payment"|"itinerary")[]):Check{const labels={invoice:"发票",order:"订单",payment:"支付",itinerary:"行程"};const found=types.map(type=>({type,values:pages.filter(p=>pageHas(p,type)).map(pageAmount).filter((n):n is number=>n!==null)}));const complete=found.every(item=>item.values.length>0);const representatives=found.map(item=>item.values.length?Math.max(...item.values):null);const numbers=representatives.filter((n):n is number=>n!==null);const consistent=complete&&numbers.length===types.length&&Math.max(...numbers)-Math.min(...numbers)<=0.01;return {title:"各材料金额一致",pass:consistent,detail:"同一笔支付的发票、订单/行程和支付材料金额必须一致；不一致时需补充说明。",evidence:found.map(item=>`${labels[item.type]}：${item.values.length?item.values.map(n=>`¥${n.toFixed(2)}`).join("/"):"未识别"}`).join("；")};}
function excelChecks(books:Workbook[]){const text=books.map(b=>b.text).join("\n");const required=["时间","往返地点","往返总金额","差旅人员","差旅原因"];const missing=required.filter(x=>!text.includes(x));const hasStudent=/\d{8,}/.test(text);const closed=/杭州.{0,12}[-至到].{1,12}/.test(text)&&has(text,["往返","返程","时间"]);return {present:books.length>0,complete:books.length>0&&!missing.length&&hasStudent,closed,missing,text};}
function baseChecks(data:ReviewInput,pages:Page[]){const checks:Check[]=[];const all=pages.map(p=>p.text).join("\n");const expected=data.header.includes("基金会")?TAX.foundation:TAX.university;const nameOk=norm(all).includes(norm(expected.name)),codeOk=norm(all).includes(norm(expected.code));checks.push({title:"发票抬头与税号正确",pass:nameOk&&codeOk,detail:`附件应同时显示 ${expected.name} 和税号 ${expected.code}。`,evidence:`抬头 ${nameOk?"✓":"×"}；税号 ${codeOk?"✓":"×"}`});const counts=[...new Set(pages.map(p=>p.file))].map(file=>({file,count:pages.filter(p=>p.file===file).length}));checks.push({title:"单个材料文件少于30页",pass:counts.length>0&&counts.every(x=>x.count<30),detail:"每个PDF材料文件均需少于30页。",evidence:counts.map(x=>`${x.file}：${x.count}页`).join("；")||"未识别到PDF页面"});return checks;}
function goodsChecks(pages:Page[]){const checks:Check[]=[];const invoices=pages.filter(p=>pageHas(p,"invoice"));const pairs=invoices.map(invoice=>({invoice,support:pages.find(page=>page.file===invoice.file&&page.page===invoice.page+1)}));const pairResults=pairs.map(({invoice,support})=>{const separate=!!support&&!pageHas(support,"invoice");return {invoice,support,format:separate};});const paired=invoices.length>0&&pairResults.every(pair=>pair.format);const formatEvidence=pairResults.map((pair,index)=>`第${index+1}组 P${pair.invoice.page}→${pair.support?`P${pair.support.page}`:"缺页"} ${pair.format?"✓":"×"}`).join("；");checks.push({title:"发票与订单/支付截图按组配对",pass:paired,detail:"材料应按“发票一页→订单截图和支付截图共一页”循环排列。",evidence:formatEvidence||"未识别到发票页"});const amountResults=pairResults.map((pair,index)=>{const invoice=pageAmount(pair.invoice);const support=pair.support?supportAmounts(pair.support):{order:[],payment:[],orderRegion:0,paymentRegion:0};const orderMatch=invoice!==null&&support.order.some(value=>Math.abs(value-invoice)<=0.01);const paymentMatch=invoice!==null&&support.payment.some(value=>Math.abs(value-invoice)<=0.01);return {index,invoice,...support,matched:orderMatch&&paymentMatch};});checks.push({title:"每组发票、订单和支付金额一致",pass:amountResults.length>0&&amountResults.every(result=>result.matched),detail:"插件会分别定位合并页中的订单截图和支付截图；两处金额都必须与同组发票一致。",evidence:amountResults.map(result=>`第${result.index+1}组：发票 ${result.invoice===null?"未识别":`¥${result.invoice.toFixed(2)}`}｜订单 ${result.order.length?result.order.map(value=>`¥${value.toFixed(2)}`).join("/"):"未识别"}｜支付 ${result.payment.length?result.payment.map(value=>`¥${value.toFixed(2)}`).join("/"):"未识别"} ${result.matched?"✓":"×"}`).join("；")});const all=pages.map(p=>p.text).join("\n");const forbidden=FORBIDDEN.filter(x=>has(all,[x]));checks.push({title:"不含个人性质或禁止报销物品",pass:forbidden.length===0,detail:"个人消费、食品、家具和其他禁止物品不能报销。",evidence:forbidden.length?`识别到：${forbidden.join("、")}`:"未识别到禁止物品"});return checks;}
function localChecks(pages:Page[]){const checks:Check[]=[];const invoices=pages.filter(p=>pageHas(p,"invoice")),trips=pages.filter(p=>pageHas(p,"itinerary"));const all=pages.map(p=>p.text).join("\n"),tripText=trips.map(p=>p.text).join("\n");const separated=invoices.length>0&&trips.length>0&&!invoices.some(p=>trips.some(t=>t.file===p.file&&t.page===p.page));checks.push({title:"发票与行程单齐全且分开放置",pass:separated,detail:"需同时提供发票和行程单，并分开页面放置。",evidence:`发票页 ${invoices.length} 个；行程页 ${trips.length} 个`});const campus=CAMPUS.filter(x=>has(tripText,[x]));checks.push({title:"每段行程至少一端为浙江大学校区",pass:trips.length>0&&campus.length>0,detail:"必须在行程单的起点或终点识别到浙江大学校区。",evidence:campus.length?campus.join("、"):"行程单中未识别到校区"});const invoiceText=invoices.map(p=>p.text).join("\n"),dateMatch=invoiceText.match(new RegExp(`${CURRENT_YEAR}[年./-]\\s*\\d{1,2}[月./-]\\s*\\d{1,2}日?`));checks.push({title:`发票开票时间在${CURRENT_YEAR}年内`,pass:!!dateMatch,detail:`发票开票日期应在 ${CURRENT_YEAR} 年内。`,evidence:dateMatch?.[0]||"未识别到开票日期"});const amounts=invoiceAmounts(pages);checks.push({title:"单张发票含税金额不超过200元",pass:amounts.length>0&&amounts.every(n=>n<=200),detail:"任一张发票含税金额大于200元均不能报销。",evidence:amounts.length?amounts.map(n=>`¥${n.toFixed(2)}`).join("、"):"未识别到价税合计"});checks.push(amountConsistencyCheck(pages,["invoice","itinerary"]));const bad=RISKY_POI.filter(x=>has(tripText,[x]));checks.push({title:"目的地业态符合报销要求",pass:trips.length>0&&bad.length===0,detail:"餐饮、娱乐、景区及商场类地点不能报销；无法判断业态时需人工确认。",evidence:bad.length?`风险地点特征：${bad.join("、")}`:trips.length?"已按地点类型词典核对，未识别到风险业态":"未识别到行程地点，需人工确认"});const station=has(tripText,["机场","火车站","高铁站","铁路杭州站","杭州东站","杭州西站"]);const travel=has(all,["火车票","铁路电子客票","航班","机票","航空运输"]);checks.push({title:"车站/机场行程与对应差旅材料一起提交",pass:!station||travel,detail:"前往车站或机场的行程必须与高铁或飞机差旅一起提交。",evidence:station?(travel?"已识别对应差旅材料":"缺少对应差旅材料"):"未涉及车站或机场"});return checks;}
function railChecks(pages:Page[],books:Workbook[]){const checks:Check[]=[];const all=pages.map(p=>p.text).join("\n");const excel=excelChecks(books);const second=has(all,["二等座","二等" ]),first=has(all,["一等座","一等"]),exception=has(all,["情况说明"])&&has(all,["二等票价","二等座票价"]);checks.push({title:"乘坐席别符合二等座要求",pass:second||(!second&&first&&exception),detail:"应乘坐二等座；一等座需附情况说明和二等座票价截图。",evidence:second?"识别到二等座":first?(exception?"识别到一等座及例外材料":"识别到一等座，但缺少情况说明或二等座票价截图"):"未识别到席别"});checks.push({title:"电子发票PDF已提交",pass:pages.some(p=>pageHas(p,"invoice")),detail:"高铁报销需提供电子发票PDF。",evidence:`识别到 ${pages.filter(p=>pageHas(p,"invoice")).length} 个发票页`});checks.push({title:"差旅Excel字段完整",pass:excel.complete,detail:"Excel需含时间、往返地点、往返总金额、差旅人员（姓名、学号）和差旅原因。",evidence:excel.present?(excel.missing.length?`缺少：${excel.missing.join("、")}；并检查姓名/学号` : "已识别要求字段和学号"):"未发现Excel附件"});checks.push({title:"往返行程形成闭环",pass:excel.closed,detail:"应从杭州出发并返回杭州。",evidence:excel.present?clip(excel.text,["往返地点","杭州"]):"未发现Excel附件"});return checks;}
function flightChecks(pages:Page[],books:Workbook[]){const checks:Check[]=[];const all=pages.map(p=>p.text).join("\n");const excel=excelChecks(books);checks.push({title:"发票或纸质行程单已提交",pass:pages.some(p=>pageHas(p,"invoice")||pageHas(p,"itinerary")),detail:"可提交电子/纸质发票原件；无发票时可用纸质行程单。"});const order=has(all,["订单","航班号","航班"]),identity=has(all,["姓名","乘机人","旅客"]),route=has(all,["出发地","目的地","起飞","到达"]),economy=has(all,["经济舱","经济舱位"]);checks.push({title:"订单截图信息完整且为经济舱",pass:order&&identity&&route&&economy,detail:"订单截图需体现姓名、起终点、航班号和经济舱舱位，并证明由填报学号人员乘坐。",evidence:`订单/航班 ${order?"✓":"×"}；姓名 ${identity?"✓":"×"}；起终点 ${route?"✓":"×"}；经济舱 ${economy?"✓":"×"}`});checks.push({title:"支付截图已提交",pass:pages.some(p=>pageHas(p,"payment")),detail:"飞机票材料需包含支付截图。",evidence:`识别到 ${pages.filter(p=>pageHas(p,"payment")).length} 个支付页`});checks.push(amountConsistencyCheck(pages,["invoice","order","payment"]));checks.push({title:"差旅Excel字段完整",pass:excel.complete,detail:"Excel需含时间、往返地点、往返总金额、差旅人员（姓名、学号）和差旅原因。",evidence:excel.present?(excel.missing.length?`缺少：${excel.missing.join("、")}`:"已识别要求字段和学号"):"未发现Excel附件"});checks.push({title:"往返行程形成闭环",pass:excel.closed,detail:"应从杭州出发并返回杭州。",evidence:excel.present?clip(excel.text,["往返地点","杭州"]):"未发现Excel附件"});return checks;}
async function readSelection(){const table=await bitable.base.getActiveTable();const view=await table.getActiveView() as IGridView;const ids=await view.getSelectedRecordIdList();if(ids.length!==1)throw new Error(ids.length?"请只勾选一条记录进行审核":"请先在表格左侧勾选一条记录");const [treasury,header,category,source,reason]=await Promise.all([table.getFieldByName(FIELD.treasury),table.getFieldByName(FIELD.header),table.getFieldByName(FIELD.category),table.getFieldByName<IAttachmentField>(FIELD.source),table.getFieldByName(FIELD.reason)]);const recordId=ids[0];const [treasuryText,headerText,categoryText,reasonText,files,urls]=await Promise.all([treasury.getCellString(recordId),header.getCellString(recordId),category.getCellString(recordId),reason.getCellString(recordId),source.getValue(recordId),source.getAttachmentUrls(recordId)]);return {recordId,reason:reasonText.trim(),treasury:treasuryText.trim(),header:headerText.trim(),category:categoryText.trim(),files,urls} as ReviewInput;}
async function refresh(){refreshBtn.disabled=true;reviewBtn.disabled=true;progress(0,1);try{setStatus("正在读取所选记录……");input=await readSelection();selectionEl.textContent=`${input.reason||"未填写报销事由"}｜${input.category||"未选择类目"}`;setStatus("记录读取完成，正在自动审核……");resultEl.innerHTML="";await review();}catch(error){input=null;selectionEl.textContent=error instanceof Error?error.message:String(error);setStatus(error instanceof Error?error.message:String(error),"error");reviewBtn.disabled=true;refreshBtn.disabled=false;}}
const GROUP_ORDER=["基础信息","材料格式","金额核对","内容合规","差旅关联"] as const;
function groupFor(title:string){if(/抬头|税号/.test(title))return"基础信息";if(/金额/.test(title))return"金额核对";if(/车站|机场/.test(title))return"差旅关联";if(/校区|开票时间|目的地|禁止报销|席别|闭环/.test(title))return"内容合规";return"材料格式";}
function checkHtml(check:Check){const reason=check.pass?"":`<p>${safe(check.detail)}</p>`;const evidence=check.evidence?`<p class="evidence">${safe(check.evidence)}</p>`:"";return `<article class="check ${check.pass?"pass":"fail"}"><span class="icon">${check.pass?"✓":"×"}</span><div><h4>${safe(check.title)}</h4>${reason}${evidence}</div></article>`;}
function render(data:ReviewInput,checks:Check[],skipped=false){const passed=checks.filter(c=>c.pass).length,allPass=checks.length>0&&passed===checks.length;const cls=skipped?"skip":allPass?"pass":"fail";const groups=GROUP_ORDER.map(group=>({group,items:checks.filter(c=>groupFor(c.title)===group)})).filter(group=>group.items.length);const grouped=groups.map(({group,items})=>`<section class="check-group"><h3 class="group-title">${group}</h3>${items.map(checkHtml).join("")}</section>`).join("");resultEl.innerHTML=`<section class="card summary ${cls}"><h2>${skipped?"无需预审":allPass?"预审通过":"预审未通过 / 需人工确认"}</h2><p>${skipped?"该记录标记为小金库，不分析报销材料。":`通过 ${passed}/${checks.length} 项；仅未通过项展开原因。`}</p><div class="meta"><span>报销事由</span><b>${safe(data.reason||"未填写")}</b><span>发票抬头</span><b>${safe(data.header||"未填写")}</b><span>报销类目</span><b>${safe(data.category||"未填写")}</b><span>材料附件</span><b>${data.files.length} 个</b></div></section>${skipped?"":`<section class="checks">${grouped}</section>`}`;}
async function review(){if(!input)return;reviewBtn.disabled=true;refreshBtn.disabled=true;resultEl.innerHTML="";try{if(input.treasury.includes("是")){render(input,[],true);setStatus("该记录属于小金库，已按规则跳过材料分析。","success");return;}if(!input.header||!input.category)throw new Error("请先填写发票抬头和报销类目");if(!input.files.length)throw new Error("未找到报销材料附件");const pages:Page[]=[],books:Workbook[]=[];const type=kind(input.category);for(let i=0;i<input.files.length;i++){const file=input.files[i],url=input.urls[i];setStatus(`正在读取 ${i+1}/${input.files.length}：${file.name}`);const response=await fetch(url);if(!response.ok)throw new Error(`附件下载失败：${file.name}`);const buffer=await response.arrayBuffer();if(isPdf(file)){pages.push(...await parsePdf(file.name,buffer,type));}else if(isImage(file)){pages.push(await parseImage(file.name,new Blob([buffer],{type:file.type})));}else if(isExcel(file)){books.push(parseWorkbook(file.name,buffer));}progress(i+1,input.files.length);}let checks=baseChecks(input,pages);if(type==="goods")checks.push(...goodsChecks(pages));else if(type==="local")checks.push(...localChecks(pages));else if(type==="rail")checks.push(...railChecks(pages,books));else if(type==="flight")checks.push(...flightChecks(pages,books));else checks.push({title:"报销类目已配置专项规则",pass:false,detail:`当前版本尚未配置“${input.category}”的专项规则，请人工审核。`});render(input,checks);setStatus(checks.every(c=>c.pass)?"所有规则均已通过。":"审核完成，请处理未勾选项目。",checks.every(c=>c.pass)?"success":"error");}catch(error){setStatus(error instanceof Error?error.message:String(error),"error");}finally{reviewBtn.disabled=!input;refreshBtn.disabled=false;}}
refreshBtn.onclick=refresh;reviewBtn.onclick=review;void refresh();
